'use client'
import './globals.css'
import { useEffect } from 'react'


export const metadata = {
  title: 'Misy',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  useEffect(() => {
    if(typeof window !== "undefined"){
      require('bootstrap/dist/js/bootstrap.min.js')
    }
  },[])


  return (
    
    <html lang="en">
    
      <body>

      {/* <Menu /> */}


        {children}

        {/* <Footer/> */}
        
        </body>
    </html>
  )
}